2 Block code đầu tiên là em test các lệnh của K-NN

In [23]:
import numpy as np
from sklearn import neighbors, datasets
from sklearn.neighbors import NearestNeighbors

iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

print('number of classes: %d' %len(np.unique(iris_y)))
print('data points: %d' %len(iris_y))

#x_train = np.array(x_train)

clf = NearestNeighbors(n_neighbors = 2)
clf.fit(x_train)

#hoods = clf.kneighbors(x_train[4], 3) 
#print(hoods)
print(x_train[4])
print(clf.kneighbors([x_train[4]]))


#from sklearn.metrics import accuracy_score
#print("Accuracy: %.2f %%" %(100 * accuracy_score(y_test, y_pred)))

number of classes: 3
data points: 150
[5.  3.6 1.4 0.2]
(array([[0.        , 0.14142136]]), array([[4, 0]]))


In [31]:
samples = [[0., 0., 0.], [0., .5, 0.], [1., 1., .5]]
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=3)
neigh.fit(samples)
#NearestNeighbors(algorithm='auto', leaf_size=30, ...)
ans = np.array(neigh.kneighbors([[1., 1., 1.]])[1][0])
print(ans)
#print(neigh.kneighbors([[1., 1., 1.]])[1].shape) 
#(array([[ 0.5]]), array([[2]]...)) 

[2 1 0]


Dưới đây là hàm K-NN cho project, mặc định  là in ra 4 ảnh.

In [0]:
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split

def KNN(img, X_data):
  #each time rebuild the KNN
  n_neighbors = 4
  clf = neighbors.kneighbors(n_neighbors)
  clf.fit(X_data)
  return np.array(neigh.kneighbors([[img]])[1][0])
  
 

In [0]:
from pylab import imread,subplot,imshow,show
import matplotlib.pyplot as plt

def print_photos_resemble(output):
  cnt = 0
  pivot = 0
  fig, ax = plt.subplots(1, 4)
  
  for file in os.listdir(folder):
    
    if file.find('.jpg') == -1:
      continue
      
    if cnt in output:
      ax[pivot].imshow(imread(folder + file))
      pivot += 1
    cnt += 1

  for i in range(4):
    ax[i].grid(False)
    ax[i].set_xticks([])
    ax[i].set_yticks([])
    
  plt.show()
    
print_photos_resemble([5,2,7,3])